name: CellMod-ng
author: Jordan Bussanich
main: com.jordanbussanich.cellmodng.CellMod
version: 1.0
description: Cellular Phones in Minecraft.
depend: [Vault]

commands:
  cell:
    description: Pull out your phone.
    usage: /cell
  ct:
    description: Create a new tower.
    usage: /ct
  send:
    description: Send a text message
    usage: /send
  number:
    description: Changes your number
    usage: /number
  directory:
    description: View phone book of phone numbers
    usage: /directory
  plan:
    description: View/Change Your Cellular Plan
    usage: /plan
  carrier:
    description: View/Create Your Carrier
    usage: /carrier